name: .NET Core

on:
    push:
        branches: [master, development]
    pull_request:
        branches: [master, development]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0
            - name: Install dependencies
              run: dotnet restore
            - name: Build Windows x86
              run: dotnet publish --configuration Release --runtime win-x86
            - name: Build Windows x64
              run: dotnet publish --configuration Release --runtime win-x64
            - name: Build Mac OSX x64
              run: dotnet publish --configuration Release --runtime osx-x64
            #- name: Build Linux x86
            #  run: dotnet build --configuration Release  --runtime linux-x86
            - name: Build Linux x64
              run: dotnet publish --configuration Release --runtime linux-x64
            - name: Build Linux ARM
              run: dotnet publish --configuration Release --runtime linux-arm
            - name: Build Linux ARM64
              run: dotnet publish --configuration Release --runtime linux-arm64
